возможность указывать имя образа gitea
dopos/dcape pull request #31
Opened 2023-03-24 06:54 UTC by knyazevaa0307

Возможность указывать имя и версию образа gitea в конфигурационном файле .env.

2023-03-24 07:20 UTC, LeKovr requested changes
Обе правки неодноначны(
Возможно, стоило сначала сформулировать проблему, которую пытаемся решить

2023-03-24 07:20 UTC, LeKovr commented on Makefile
> +PG_HOSTNAME      ?= dcape-db
Текущий hostname: `db`. Если его убрать в переменную и поменять дефолтное значение - разве это не развалит конфиги связанных приложений? Предлагаю вариант `?= db`

2023-03-24 07:20 UTC, LeKovr commented on apps/gitea/Makefile
> +GITEA_VER0         ?= gitea/gitea:1.10.0
Такое изменение развалит текущие конфиги. Предлагаю добавить `GITEA_IMAGE` и включить ее в проверку версий как `GITEA_IMAGE0`. Но надо определиться с его содержимым
1. `gitea/gitea` - так текущие конфиги не придется менять
2. `gitea/gitea:1.10.0` - так можно убрать все `_VER` и `_VER0`

2023-03-29 11:07 UTC, abhinand75 commented on Makefile
> +PG_HOSTNAME      ?= dcape-db
`db` сейчас не текущий hostname, а имя сервиса в compose, текущий hostname - это генерируемый докером идентификатор. Смысл задавать формализованный hostname в  том, чтобы обеспечить возможность работы утилит бэкапирования и обновления. Xorax добавление HOSTNAME влечет не только объявление переменной, но и ее использование :)

2023-03-29 11:11 UTC, abhinand75 commented on apps/gitea/Makefile
> +GITEA_VER0         ?= gitea/gitea:1.10.0
По поводу описание проблемы, мы добавляем в gitea различные рендеры и это требует пересборки образа, что влечет необходимость использовать кастомный образ и возможность его указания через конфиг. Можно в одной переменной, можно по классике на имя образа и версии по переменной. Развалит текущие конфиги - это те которые уже используется на серверах? Если так, то мы скорректируем, или первая версия еще где-то используется?

2023-03-29 11:15 UTC, LeKovr commented on Makefile
> +PG_HOSTNAME      ?= dcape-db
В настоящее время в dcape-app-* строка соединения задается так:
`postgres://${PGUSER}:${PGPASSWORD}@db/${PGDATABASE}?sslmode=disable`
т.е. хост доступен под именем `db`, я это имел ввиду. Если явное указание hostname этот факт не испортит, то проблем нет.

2023-03-29 11:34 UTC, LeKovr commented on apps/gitea/Makefile
> +GITEA_VER0         ?= gitea/gitea:1.10.0
Цель понятна, мой посыл о том, чтобы доработки не ломали совместимость. И в v2 они тоже могут понадобиться

2023-03-29 11:46 UTC, abhinand75 commented on Makefile
> +PG_HOSTNAME      ?= dcape-db
Да, это никак не испортит, хотим поменять только hostname внутри контейнера, 
```
docker exec -ti dcape_db_1 bash
root@2f0a8f42df9f:/# echo $HOSTNAME
2f0a8f42df9f

``` 
заменить этот ID на формализованное имя. Xorax подготовит корректный PR.

2023-03-31 12:25 UTC, abhinand75 commented
Все изменения проверены и корректно работают.

2023-03-31 15:45 UTC, LeKovr commented
"Возможно, стоило сначала сформулировать проблему, которую пытаемся решить"
Все обсудили и тут под финал убирается контроль версии gitea ((
Мне такое решение не кажется очевидным. Если используется стандартный образ gitea, то в чем причина удаления контроля версий? Предлагаю так его и доработать.

2023-04-03 16:33 UTC, LeKovr approved these changes

2023-04-03 16:34 UTC, merged